version: 1.0.{build}
max_jobs: 2
image: Visual Studio 2015
before_build:
- ps: nuget restore ChakraCore\Build\Chakra.Core.sln
build_script:
  - ps: >-
    git submodule update --init

	md .\ChakraCore\Build\VcBuild\bin\x86_Release
	md .\ChakraCore\Build\VcBuild\bin\x64_Release
	md .\ChakraCore\Build\VcBuild\bin\arm_Release

	md .\ChakraCore\Build\VcBuild\bin\x86_Release\buildlogs
	md .\ChakraCore\Build\VcBuild\bin\x64_Release\buildlogs
	md .\ChakraCore\Build\VcBuild\bin\arm_Release\buildlogs

after_build:
- ps: .\NuGet\package.ps1
artifacts:
- path: .\NuGet\Artifacts\*.nupkg
  name: NuGet