version: 1.0.{build}
before_build:
- ps: nuget restore ChakraCore\Build\Chakra.Core.sln
build:
  verbosity: normal
after_build:
- ps: .\NuGet\package.ps1
artifacts:
- path: .\NuGet\Artifacts\*.nupkg
  name: NuGet